apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-webapp
  template:
    metadata:
      labels:
        app: todo-webapp
    spec:
      containers:
      - name: todo-container
        image: 84patjak/todoapp:d1447e051c7d270bf7f9343bc09124d2a23549d8
        ports:
        - containerPort: 80
        envFrom: 
        - configMapRef:
            name: app-config